version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    logging:
      options:
         max-size: 1g

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    logging:
      options:
         max-size: 1g

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    logging:
      options:
         max-size: 1g

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 6.9.2
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: https://rpc.dev.deriw.com/
        ETHEREUM_JSONRPC_TRACE_URL: htts://rpc.dev.deriw.com/
        ETHEREUM_JSONRPC_WS_URL: wss://rpc.dev.eriw.com/ws
        CHAIN_ID: '44474237230'
    logging:
      options:
         max-size: 1g

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    logging:
      options:
         max-size: 1g

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    logging:
      options:
         max-size: 1g

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    logging:
      options:
         max-size: 1g

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    logging:
      options:
         max-size: 1g

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    logging:
      options:
         max-size: 1g

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    logging:
      options:
         max-size: 1g

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    logging:
      options:
         max-size: 1g

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    logging:
      options:
         max-size: 1g
