version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    logging:
      options:
         max-size: 1g

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    logging:
      options:
         max-size: 1g

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    logging:
      options:
         max-size: 1g

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 9.0.1
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: https://rpc.prod.deriw.com/
        ETHEREUM_JSONRPC_TRACE_URL: https://rpc.prod.deriw.com/
        ETHEREUM_JSONRPC_WS_URL: ws://rpc.prod.deriw.com
        CHAIN_ID: '2886'
    logging:
      options:
         max-size: 1g

  nft_media_handler:
    depends_on:
      - backend
    extends:
      file: ./services/nft_media_handler.yml
      service: nft_media_handler
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 9.0.1

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    logging:
      options:
         max-size: 1g

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    logging:
      options:
         max-size: 1g

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    logging:
      options:
         max-size: 1g

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    logging:
      options:
         max-size: 1g

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    logging:
      options:
         max-size: 1g

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    logging:
      options:
         max-size: 1g

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    logging:
      options:
         max-size: 1g

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    logging:
      options:
         max-size: 1g